service: serverless-task-1
custom:
  usersTableName: 'Users'

provider:
  name: aws
  runtime: java8
  region: us-east-1
  timeout: 10
  memorySize: 1024
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"
  environment:
    USERS_TABLE_NAME: ${self:custom.usersTableName}

package:
  artifact: target/task1-dev.jar

functions:
  fetch:
    handler: com.serverless.ListUserHandler
    events:
      - http:
          method: GET
          path: /users

  fetchById:
    handler: com.serverless.GetUserHandler
    events:
      - http:
          method: GET
          path: /users/{id}

  add:
    handler: com.serverless.CreateUserHandler
    events:
      - http:
          method: POST
          path: /users

  delete:
    handler: com.serverless.DeleteUserHandler
    events:
      - http:
          method: DELETE
          path: /users/{id}

resources:
  Resources:
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
